config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root 'posts#index', as: :authenticated_root
  end
  
  root "posts#index"
  resources :posts do
      resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  
  validates :content, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    
    has_many :comments
    
    validates :content, presence: true
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params[:comment].permit(:content))
        @comment.user_id = current_user.id if current_user
        
        if @comment.save
            redirect_to post_path(@post)
        else
            render 'new'
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_filter :authenticate_user!
    before_action :set_posts, only: [:show]
    
    def index
        @posts = Post.all.order("created_at DESC")
    end
    
    def new
        @post = current_user.posts.build
    end 
    
    def create 
        @post = current_user.posts.build(posts_params)
        
        if @post.save
            redirect_to @post
        else
            render 'new'
        end
    end
    
    def show
    end
    
    
    private
    def posts_params
        params.require(:post).permit(:title, :content)
    end
    
    def set_posts
        @post = Post.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment
    %p 
        =comment.user.email 
        says
        =comment.content

app/views/comments/_form.html.haml
.panel-body
    = simple_form_for([@post, @post.comments.build]) do |f|
        =f.input :content, input_html: {class: 'form-control'}
        =f.submit

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Rails Forum
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
  %link{"rel" => "stylesheet", "href" => "http://fonts.googleapis.com/css?family=Lato:300,400,700", "type" => "text/css"}
  = javascript_include_tag 'application', 'data-turbolinks-track' => true 
  = csrf_meta_tags

%body
  %header.main_header.clearfix
    .wrapper
      #logo
        %p 
        = link_to "Rails Forum", posts_url
      #buttons
        -if user_signed_in?
          = link_to "New Post", new_post_path
          = link_to "Log Out" , destroy_user_session_path, method: :delete
        -else
          = link_to "Sign In", new_user_session_path
          = link_to "Sign Up", new_user_registration_path
      
  .wrapper
    %p.notice= notice
    %p.alert= alert
  
  .wrapper  
    =yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
    = f.input :title, input_html: {class: 'form-control'}
    = f.input :content, input_html: {class:'form-control'}
    
    = f.submit

app/views/posts/index.html.haml
#posts
    - @posts.each do |post|
        .post
            %h2.title
                = link_to post.title, post_url(post.id)
            %p.date
                Created
                = time_ago_in_words(post.created_at)
                ago by
                =post.user.email

app/views/posts/new.html.haml
%h1 New Post

= render 'form'

app/views/posts/show.html.haml
%h1= @post.title

%p= @post.content

#comments
    %h2
        Comments
    %h5
        =@post.comments.count 
        -if @post.comments.count == 1
            Comment
        -else
            Comments
        
    %h2 
    = render @post.comments
    
    
    %h3 Reply to Thread
    = render "comments/form"